### PR TITLE
Add way to distinguish between not found keys and other errors

### LINKED ISSUE #15: add a notFound property to the Error
This is also present in Level, and it is really useful to differentiate between network errors and not found keys.

### PR DESCRIPTION
**Pull request by jnordberg**
Fixes #15

### CODE REVIEW

**Comment by jnordberg** [comment]
@maxogden Let me know if you want some help maintaining this module, I'd be happy to do it

**Comment by maxogden** [comment]
@jnordberg yes that would be great, as long as you dont break the spec too much w/o feedback from users/other contributors

**Comment by jnordberg** [comment]
@maxogden Noted :) Thank you! same username on npm if you are willing to grant me publish

**Comment by bcomnes** [comment]
This was a breaking change.

**Pull request merged**
